version: 2.1
orbs:
  react-native: react-native-community/react-native@4.4.2
jobs:
  checkout_code:
    executor: react-native/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
workflows:
  build-and-test:
    jobs:
      - checkout_code
      - react-native/ios_build_and_test:
          build_configuration: Release
          device: iPhone X
          project_path: ios/osaka.xcodeproj
          scheme: Example
