export const AGREEMENTS_MOCKDATA = {
  agreements: [
    {
      id: 814,
      agreement_template_id: 1,
      created: '2020-08-21T16:30:58.921003+00:00',
      last_modified: null,
      agreement_events: [
        {
          type: 'texted',
          id: 705,
        },
      ],
      address: {
        city: 'North Chandlerfurt',
        county: null,
        id: 4,
        line1: '0391 Zieme Parks',
        line2: 'Bldg C',
        us_state: 'SD',
        postal_code: '85831',
      },
      addressByShippingAddressId: {
        city: 'North Chandlerfurt',
        county: null,
        id: 4,
        line2: 'Bldg C',
        line1: '0391 Zieme Parks',
        us_state: 'SD',
        postal_code: '85831',
      },
      contact: {
        name_first: 'Dudley',
        name_last: 'Koelpin',
        id: 10,
      },
      contact_id: 10,
      line_items: [
        {
          agreement_id: 814,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 0,
          price: 270000,
          qty: 1,
          id: 897,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
        {
          agreement_id: 814,
          catalog_item_id: 12,
          current_cost: 23320,
          discount: 0,
          price: 50000,
          qty: 1,
          id: 898,
          catalog_item: {
            name: 'Automatic Folding Footrest',
          },
        },
      ],
      number: '13',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 4,
      signature: null,
      user: {
        prefix: 'LH',
        pres: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
    },
    {
      id: 813,
      agreement_template_id: 1,
      created: '2020-08-21T16:28:13.689353+00:00',
      last_modified: null,
      agreement_events: [
        {
          type: 'texted',
          id: 704,
        },
      ],
      address: {
        city: 'Cyrustown',
        county: null,
        id: 11,
        line1: '401 Aglae Expressway',
        line2: null,
        us_state: 'MA',
        postal_code: '64195',
      },
      addressByShippingAddressId: {
        city: 'Cyrustown',
        county: null,
        id: 11,
        line2: null,
        line1: '401 Aglae Expressway',
        us_state: 'MA',
        postal_code: '64195',
      },
      contact: {
        name_first: 'Emmet',
        name_last: 'Lockman',
        id: 4,
      },
      contact_id: 4,
      line_items: [
        {
          agreement_id: 813,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 0,
          price: 270000,
          qty: 1,
          id: 894,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
        {
          agreement_id: 813,
          catalog_item_id: 6,
          current_cost: 29260,
          discount: 0,
          price: 50000,
          qty: 1,
          id: 895,
          catalog_item: {
            name: 'Automatic Folding Footrest',
          },
        },
        {
          agreement_id: 813,
          catalog_item_id: 9,
          current_cost: 36740,
          discount: 0,
          price: 70000,
          qty: 1,
          id: 896,
          catalog_item: {
            name: 'Manual Folding Rail',
          },
        },
      ],
      number: '12',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 11,
      signature: null,
      user: {
        prefix: 'LH',
        pres: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
    },
  ],
};
