export const AGREEMENT_DETAILS_MOCKDATA = {
  id: 814,
  agreement_template_id: 1,
  created: '2020-08-21T16:30:58.921003+00:00',
  last_modified: null,
  agreement_events: [
    {
      type: 'texted',
      id: 705,
    },
  ],
  address: {
    city: 'North Chandlerfurt',
    county: null,
    id: 4,
    line1: '0391 Zieme Parks',
    line2: 'Bldg C',
    us_state: 'SD',
    postal_code: '85831',
  },
  addressByShippingAddressId: {
    city: 'North Chandlerfurt',
    county: null,
    id: 4,
    line2: 'Bldg C',
    line1: '0391 Zieme Parks',
    us_state: 'SD',
    postal_code: '85831',
  },
  contact: {
    name_first: 'Dudley',
    name_last: 'Koelpin',
    id: 10,
  },
  contact_id: 10,
  line_items: [
    {
      agreement_id: 814,
      catalog_item_id: 1,
      current_cost: 155000,
      discount: 0,
      price: 270000,
      qty: 1,
      id: 897,
      catalog_item: {
        name: 'Elan SRE-3050',
      },
    },
    {
      agreement_id: 814,
      catalog_item_id: 12,
      current_cost: 23320,
      discount: 0,
      price: 50000,
      qty: 1,
      id: 898,
      catalog_item: {
        name: 'Automatic Folding Footrest',
      },
    },
  ],
  number: '13',
  revision: 0,
  sales_tax_rate: 8,
  shipping_address_id: 4,
  signature: null,
  user: {
    prefix: 'LH',
    prefs: {
      passcode: null,
    },
    public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
    name_last: 'Hermann',
    name_first: 'Lacy',
    google_id: null,
    email: 'elisha61@hotmail.com',
    default_sales_tax_rate: 8,
    organization_id: 1,
  },
  user_id: 1,
};
