export const CONTACTS_MOCKDATA = {
  contacts: [
    {
      id: 1,
      email: 'alana.nitzsche44@gmail.com',
      name_first: 'Irving',
      name_last: 'Marvin',
      title: 'Mrs.',
      company: 'Jacobs LLC',
      phone_home: '+18581950948',
      phone_mobile: '+18653374781',
      phone_office: null,
      address_id: 7,
      address: {
        city: 'Andersonhaven',
        lat: null,
        id: 7,
        county: null,
        line1: '0558 Jacobi Street',
        line2: 'Apt 4A',
        postal_code: '49001',
        us_state: 'AR',
      },
      agreements: [
        {
          agreement_events: [
            {
              type: 'texted',
              id: 893,
            },
          ],
          address: {
            city: 'Andersonhaven',
            county: null,
            id: 7,
            line1: '0558 Jacobi Street',
            line2: 'Apt 4A',
            us_state: 'AR',
            postal_code: '49001',
          },
          addressByShippingAddressId: {
            city: 'Andersonhaven',
            county: null,
            id: 7,
            line2: 'Apt 4A',
            line1: '0558 Jacobi Street',
            us_state: 'AR',
            postal_code: '49001',
          },
          contact: {
            name_first: 'Irving',
            name_last: 'Marvin',
            id: 1,
          },
          contact_id: 1,
          line_items: [
            {
              agreement_id: 1003,
              catalog_item_id: 1,
              current_cost: 155000,
              discount: 10000,
              price: 270000,
              qty: 1,
              order: null,
              id: 1092,
              catalog_item: {
                name: 'Elan SRE-3050',
              },
            },
          ],
          number: '2',
          revision: 0,
          sales_tax_rate: 8,
          shipping_address_id: 7,
          signature: null,
          user: {
            prefix: 'LH',
            prefs: {
              passcode: null,
            },
            public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
            name_last: 'Hermann',
            name_first: 'Lacy',
            google_id: null,
            email: 'elisha61@hotmail.com',
            default_sales_tax_rate: 8,
            organization_id: 1,
          },
          user_id: 1,
        },
      ],
    },
  ],
};
