export const CONTACT_DETAILS_MOCKDATA = {
  id: 1,
  email: 'alana.nitzsche44@gmail.com',
  name_first: 'Irving',
  name_last: 'Marvin',
  title: 'Mrs.',
  company: 'Jacobs LLC',
  phone_home: '+18581950948',
  phone_mobile: '+18653374781',
  phone_office: null,
  address_id: 7,
  address: {
    city: 'Andersonhaven',
    lat: null,
    id: 7,
    county: null,
    line1: '0558 Jacobi Street',
    line2: 'Apt 4A',
    postal_code: '49001',
    us_state: 'AR',
  },
  agreements: [
    {
      id: 1021,
      agreement_template_id: 1,
      agreement_events: [
        {
          type: 'accepted',
          id: 900,
        },
      ],
      address: {
        city: 'Andersonhaven',
        county: null,
        id: 7,
        line1: '0558 Jacobi Street',
        line2: 'Apt 4A',
        us_state: 'AR',
        postal_code: '49001',
      },
      addressByShippingAddressId: {
        city: 'Andersonhaven',
        county: null,
        id: 7,
        line2: 'Apt 4A',
        line1: '0558 Jacobi Street',
        us_state: 'AR',
        postal_code: '49001',
      },
      contact: {
        name_first: 'Irving',
        name_last: 'Marvin',
        id: 1,
      },
      contact_id: 1,
      line_items: [
        {
          agreement_id: 1021,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 0,
          price: 270000,
          qty: 1,
          order: null,
          id: 1149,
          taxable: true,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
        {
          agreement_id: 1021,
          catalog_item_id: 7,
          current_cost: 0,
          discount: 0,
          price: 0,
          qty: 1,
          order: null,
          id: 1150,
          taxable: true,
          catalog_item: {
            name: 'Power-Assisted Swivel Seat',
          },
        },
        {
          agreement_id: 1021,
          catalog_item_id: 6,
          current_cost: 0,
          discount: 0,
          price: 0,
          qty: 1,
          order: null,
          id: 1151,
          taxable: true,
          catalog_item: {
            name: 'Automatic Folding Footrest',
          },
        },
        {
          agreement_id: 1021,
          catalog_item_id: 4,
          current_cost: 0,
          discount: 0,
          price: 0,
          qty: 1,
          order: null,
          id: 1152,
          taxable: true,
          catalog_item: {
            name: 'Power Folding Rail',
          },
        },
        {
          agreement_id: 1021,
          catalog_item_id: 3,
          current_cost: 13420,
          discount: 0,
          price: 25500,
          qty: 1,
          order: null,
          id: 1153,
          taxable: true,
          catalog_item: {
            name: "20' Rail Installation Kit",
          },
        },
      ],
      number: '23',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 7,
      signature: null,
      user: {
        prefix: 'LH',
        prefs: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
      agreement_template: {
        name: 'Bruno Straight Stairlift',
        opts: {
          color: 'rgb(200, 170, 10)',
          payment_schedule: [
            {
              type: 'percentage',
              value: 0.1,
              description: 'Deposit',
            },
            {
              type: 'percentage',
              value: 0.9,
              description: 'Balance due upon installation',
            },
          ],
        },
        id: 1,
      },
    },
    {
      id: 1003,
      agreement_template_id: 1,
      agreement_events: [
        {
          type: 'texted',
          id: 893,
        },
      ],
      address: {
        city: 'Andersonhaven',
        county: null,
        id: 7,
        line1: '0558 Jacobi Street',
        line2: 'Apt 4A',
        us_state: 'AR',
        postal_code: '49001',
      },
      addressByShippingAddressId: {
        city: 'Andersonhaven',
        county: null,
        id: 7,
        line2: 'Apt 4A',
        line1: '0558 Jacobi Street',
        us_state: 'AR',
        postal_code: '49001',
      },
      contact: {
        name_first: 'Irving',
        name_last: 'Marvin',
        id: 1,
      },
      contact_id: 1,
      line_items: [
        {
          agreement_id: 1003,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 10000,
          price: 270000,
          qty: 1,
          order: null,
          id: 1092,
          taxable: true,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
      ],
      number: '2',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 7,
      signature: null,
      user: {
        prefix: 'LH',
        prefs: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
      agreement_template: {
        name: 'Bruno Straight Stairlift',
        opts: {
          color: 'rgb(200, 170, 10)',
          payment_schedule: [
            {
              type: 'percentage',
              value: 0.1,
              description: 'Deposit',
            },
            {
              type: 'percentage',
              value: 0.9,
              description: 'Balance due upon installation',
            },
          ],
        },
        id: 1,
      },
    },
    {
      id: 1007,
      agreement_template_id: 1,
      agreement_events: [
        {
          type: 'texted',
          id: 896,
        },
      ],
      address: null,
      addressByShippingAddressId: {
        city: 'Andersonhaven',
        county: null,
        id: 7,
        line2: 'Apt 4A',
        line1: '0558 Jacobi Street',
        us_state: 'AR',
        postal_code: '49001',
      },
      contact: {
        name_first: 'Irving',
        name_last: 'Marvin',
        id: 1,
      },
      contact_id: 1,
      line_items: [
        {
          agreement_id: 1007,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 10000,
          price: 270000,
          qty: 1,
          order: null,
          id: 1104,
          taxable: true,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
      ],
      number: '1',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 7,
      signature: null,
      user: {
        prefix: 'LH',
        prefs: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
      agreement_template: {
        name: 'Bruno Straight Stairlift',
        opts: {
          color: 'rgb(200, 170, 10)',
          payment_schedule: [
            {
              type: 'percentage',
              value: 0.1,
              description: 'Deposit',
            },
            {
              type: 'percentage',
              value: 0.9,
              description: 'Balance due upon installation',
            },
          ],
        },
        id: 1,
      },
    },
    {
      id: 1010,
      agreement_template_id: 1,
      agreement_events: [],
      address: null,
      addressByShippingAddressId: {
        city: 'Andersonhaven',
        county: null,
        id: 7,
        line2: 'Apt 4A',
        line1: '0558 Jacobi Street',
        us_state: 'AR',
        postal_code: '49001',
      },
      contact: {
        name_first: 'Irving',
        name_last: 'Marvin',
        id: 1,
      },
      contact_id: 1,
      line_items: [
        {
          agreement_id: 1010,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 10000,
          price: 270000,
          qty: 1,
          order: null,
          id: 1114,
          taxable: true,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
      ],
      number: '1',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 7,
      signature: null,
      user: {
        prefix: 'LH',
        prefs: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
      agreement_template: {
        name: 'Bruno Straight Stairlift',
        opts: {
          color: 'rgb(200, 170, 10)',
          payment_schedule: [
            {
              type: 'percentage',
              value: 0.1,
              description: 'Deposit',
            },
            {
              type: 'percentage',
              value: 0.9,
              description: 'Balance due upon installation',
            },
          ],
        },
        id: 1,
      },
    },
    {
      id: 1008,
      agreement_template_id: 1,
      agreement_events: [],
      address: null,
      addressByShippingAddressId: {
        city: 'Andersonhaven',
        county: null,
        id: 7,
        line2: 'Apt 4A',
        line1: '0558 Jacobi Street',
        us_state: 'AR',
        postal_code: '49001',
      },
      contact: {
        name_first: 'Irving',
        name_last: 'Marvin',
        id: 1,
      },
      contact_id: 1,
      line_items: [
        {
          agreement_id: 1008,
          catalog_item_id: 10,
          current_cost: 73040,
          discount: 0,
          price: 140000,
          qty: 1,
          order: 1,
          id: 1111,
          taxable: true,
          catalog_item: {
            name: 'Power Folding Rail',
          },
        },
        {
          agreement_id: 1008,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 20000,
          price: 270000,
          qty: 1,
          order: 0,
          id: 1105,
          taxable: true,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
      ],
      number: '1',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 7,
      signature: null,
      user: {
        prefix: 'LH',
        prefs: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
      agreement_template: {
        name: 'Bruno Straight Stairlift',
        opts: {
          color: 'rgb(200, 170, 10)',
          payment_schedule: [
            {
              type: 'percentage',
              value: 0.1,
              description: 'Deposit',
            },
            {
              type: 'percentage',
              value: 0.9,
              description: 'Balance due upon installation',
            },
          ],
        },
        id: 1,
      },
    },
  ],
};
