export const DASHBOARD_MOCKDATA = {
  agreements: [
    {
      agreement_events: [],
      id: 1001,
      address: {
        city: 'Hermanborough',
        county: null,
        id: 16,
        line1: '784 Sheridan Ridge',
        line2: 'Bldg C',
        us_state: 'TN',
        postal_code: '42982-8790',
      },
      addressByShippingAddressId: {
        city: 'Hermanborough',
        county: null,
        id: 16,
        line2: 'Bldg C',
        line1: '784 Sheridan Ridge',
        us_state: 'TN',
        postal_code: '42982-8790',
      },
      contact: {
        name_first: 'Eveline',
        name_last: 'Bergnaum',
        id: 12,
      },
      contact_id: 12,
      line_items: [
        {
          agreement_id: 1001,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 0,
          price: 270000,
          qty: 1,
          id: 1088,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
      ],
      number: '17',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 16,
      signature: null,
      user: {
        prefix: 'LH',
        prefs: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
    },
    {
      agreement_events: [],
      id: 1000,
      address: {
        city: 'Zorafurt',
        county: null,
        id: 20,
        line1: '8984 Albina Plaza',
        line2: null,
        us_state: 'AR',
        postal_code: '40936',
      },
      addressByShippingAddressId: {
        city: 'Zorafurt',
        county: null,
        id: 20,
        line2: null,
        line1: '8984 Albina Plaza',
        us_state: 'AR',
        postal_code: '40936',
      },
      contact: {
        name_first: 'Nick',
        name_last: 'Schowalter',
        id: 5,
      },
      contact_id: 5,
      line_items: [
        {
          agreement_id: 1000,
          catalog_item_id: 1,
          current_cost: 155000,
          discount: 0,
          price: 270000,
          qty: 1,
          id: 1086,
          catalog_item: {
            name: 'Elan SRE-3050',
          },
        },
        {
          agreement_id: 1000,
          catalog_item_id: 11,
          current_cost: 36740,
          discount: 0,
          price: 79000,
          qty: 1,
          id: 1087,
          catalog_item: {
            name: 'Power-Assisted Swivel Seat',
          },
        },
      ],
      number: '16',
      revision: 0,
      sales_tax_rate: 8,
      shipping_address_id: 20,
      signature: null,
      user: {
        prefix: 'LH',
        prefs: {
          passcode: null,
        },
        public_id: '8d806ff5-0c68-430c-956d-42f2f3dd3d87',
        name_last: 'Hermann',
        name_first: 'Lacy',
        google_id: null,
        email: 'elisha61@hotmail.com',
        default_sales_tax_rate: 8,
        organization_id: 1,
      },
      user_id: 1,
    },
  ],
};

export const TILE_MOCKDATA = {
  agreement: {
    created: '2020-06-22T18:24:12.124733+00:00',
    agreement_template_id: 1,
    number: 'PF8848',
    last_modified: null,
    id: 1,
    public_id: 'de5f7e28-e25e-4c03-b50c-1342fd6721a1',
    addressByBillingAddressId: {
      city: 'Andersonhaven',
      us_state: 'AR',
    },
    contact: {
      name_last: 'Lindgren',
      name_first: 'Linnie',
    },
    address: {
      city: 'New Barrettport',
      us_state: 'MT',
    },
  },
  color: '#ababab',
};
